{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "missing-table.fullname" . }}-tls
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "missing-table.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- range .Values.ingress.tls }}
  secretName: {{ .secretName }}
  {{- end }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  {{- range .Values.ingress.hosts }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
